[project]
name = "career-hello"
version = "0.1.0"
description = "Phase 0 smoke test — bukti env uv jalan"
readme = "README.md"
authors = [
    { name = "krsnmlna1", email = "krsnmlna1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
career-hello = "career_hello:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
